name: 10000 Miles of Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61064
title: Todd Rigione
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#352923'
    - '#e2d599'
    - '#678f94'
    - '#c35f2a'
    - '#ac293b'
  brandStrength: 0.625
  lightness: 0.04351994930766523
  saturation: 0.7849897141568363
  rhythmicContrast: 0.3528894782066345
purpose: []
