name: 10000 Miles of Art
favicon: null
layout_spectrum: 0.45717
typography_spectrum: 0.61064
title: Todd Rigione
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d0ca93'
    - '#797870'
    - '#693f2b'
    - '#044d5d'
  brandStrength: 0.625
  lightness: 0.04351994930766523
  saturation: 0.7849897141568363
  rhythmicContrast: 0.3528894782066345
purpose: []
